# Generated by Django 4.1.7 on 2023-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=250, null=True)),
                ("file_name", models.CharField(max_length=250, null=True)),
                ("type", models.CharField(max_length=250, null=True)),
                ("tool_type", models.CharField(max_length=250, null=True)),
                ("created_on", models.DateTimeField(null=True)),
                ("created_by", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "history",
            },
        ),
    ]
